const dogs = [
  {
    id: 1,
    image: "https://cdn2.thedogapi.com/images/BJa4kxc4X.jpg",
    name: "Affenpinscher",
    height: { imperial: "9 - 11.5", metric: "23 - 29" },
    weight: { imperial: "6 - 13", metric: "3 - 6" },
    life_span: "10 - 12 years",
    temperament: "Stubborn, Curious, Playful, Adventurous, Active, Fun-loving",
  },
  {
    id: 2,
    image: "https://cdn2.thedogapi.com/images/hMyT4CDXR.jpg",
    name: "Afghan Hound",
    height: { imperial: "25 - 27", metric: "64 - 69" },
    weight: { imperial: "50 - 60", metric: "23 - 27" },
    life_span: "10 - 13 years",
    temperament: "Aloof, Clownish, Dignified, Independent, Happy",
  },
  {
    id: 3,
    image: "https://cdn2.thedogapi.com/images/rkiByec47.jpg",
    name: "African Hunting Dog",
    height: { imperial: "30", metric: "76" },
    weight: { imperial: "44 - 66", metric: "20 - 30" },
    life_span: "11 years",
    temperament: "Wild, Hardworking, Dutiful",
  },
  {
    id: 4,
    image: "https://cdn2.thedogapi.com/images/1-7cgoZSh.jpg",
    name: "Airedale Terrier",
    height: { imperial: "21 - 23", metric: "53 - 58" },
    weight: { imperial: "40 - 65", metric: "18 - 29" },
    life_span: "10 - 13 years",
    temperament:
      "Outgoing, Friendly, Alert, Confident, Intelligent, Courageous",
  },
  {
    id: 5,
    image: "https://cdn2.thedogapi.com/images/26pHT3Qk7.jpg",
    name: "Akbash Dog",
    height: { imperial: "28 - 34", metric: "71 - 86" },
    weight: { imperial: "90 - 120", metric: "41 - 54" },
    life_span: "10 - 12 years",
    temperament: "Loyal, Independent, Intelligent, Brave",
  },
  {
    id: 6,
    image: "https://cdn2.thedogapi.com/images/BFRYBufpm.jpg",
    name: "Akita",
    height: { imperial: "24 - 28", metric: "61 - 71" },
    weight: { imperial: "65 - 115", metric: "29 - 52" },
    life_span: "10 - 14 years",
    temperament:
      "Docile, Alert, Responsive, Dignified, Composed, Friendly, Receptive, Faithful, Courageous",
  },
  {
    id: 7,
    image: "https://cdn2.thedogapi.com/images/33mJ-V3RX.jpg",
    name: "Alapaha Blue Blood Bulldog",
    height: { imperial: "18 - 24", metric: "46 - 61" },
    weight: { imperial: "55 - 90", metric: "25 - 41" },
    life_span: "12 - 13 years",
    temperament: "Loving, Protective, Trainable, Dutiful, Responsible",
  },
  {
    id: 8,
    image: "https://cdn2.thedogapi.com/images/-HgpNnGXl.jpg",
    name: "Alaskan Husky",
    height: { imperial: "23 - 26", metric: "58 - 66" },
    weight: { imperial: "38 - 50", metric: "17 - 23" },
    life_span: "10 - 13 years",
    temperament: "Friendly, Energetic, Loyal, Gentle, Confident",
  },
  {
    id: 9,
    image: "https://cdn2.thedogapi.com/images/dW5UucTIW.jpg",
    name: "Alaskan Malamute",
    height: { imperial: "23 - 25", metric: "58 - 64" },
    weight: { imperial: "65 - 100", metric: "29 - 45" },
    life_span: "12 - 15 years",
    temperament: "Friendly, Affectionate, Devoted, Loyal, Dignified, Playful",
  },
  {
    id: 10,
    image: "https://cdn2.thedogapi.com/images/pk1AAdloG.jpg",
    name: "American Bulldog",
    height: { imperial: "22 - 27", metric: "56 - 69" },
    weight: { imperial: "60 - 120", metric: "27 - 54" },
    life_span: "10 - 12 years",
    temperament:
      "Friendly, Assertive, Energetic, Loyal, Gentle, Confident, Dominant",
  },
  {
    id: 11,
    image: "https://cdn2.thedogapi.com/images/sqQJDtbpY.jpg",
    name: "American Bully",
    height: { imperial: "14 - 17", metric: "36 - 43" },
    weight: { imperial: "30 - 150", metric: "14 - 68" },
    life_span: "8 – 15 years",
    temperament:
      "Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous",
  },
  {
    id: 12,
    image: "https://cdn2.thedogapi.com/images/Bymjyec4m.jpg",
    name: "American Eskimo Dog",
    height: { imperial: "15 - 19", metric: "38 - 48" },
    weight: { imperial: "20 - 40", metric: "9 - 18" },
    life_span: "12 - 15 years",
    temperament: "Friendly, Alert, Reserved, Intelligent, Protective",
  },
  {
    id: 13,
    image: "https://cdn2.thedogapi.com/images/_gn8GLrE6.jpg",
    name: "American Eskimo Dog (Miniature)",
    height: { imperial: "9 - 12", metric: "23 - 30" },
    weight: { imperial: "7 - 10", metric: "3 - 5" },
    life_span: "13 – 15 years",
    temperament: "Friendly, Alert, Reserved, Intelligent, Protective",
  },
  {
    id: 14,
    image: "https://cdn2.thedogapi.com/images/S14n1x9NQ.jpg",
    name: "American Foxhound",
    height: { imperial: "21 - 28", metric: "53 - 71" },
    weight: { imperial: "65 - 75", metric: "29 - 34" },
    life_span: "8 - 15 years",
    temperament:
      "Kind, Sweet-Tempered, Loyal, Independent, Intelligent, Loving",
  },
  {
    id: 15,
    image: "https://cdn2.thedogapi.com/images/HkC31gcNm.jpg",
    name: "American Pit Bull Terrier",
    height: { imperial: "17 - 21", metric: "43 - 53" },
    weight: { imperial: "30 - 60", metric: "14 - 27" },
    life_span: "10 - 15 years",
    temperament:
      "Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous",
  },
  {
    id: 16,
    image: "https://cdn2.thedogapi.com/images/rJIakgc4m.jpg",
    name: "American Staffordshire Terrier",
    height: { imperial: "17 - 19", metric: "43 - 48" },
    weight: { imperial: "50 - 60", metric: "23 - 27" },
    life_span: "12 - 15 years",
    temperament: "Tenacious, Friendly, Devoted, Loyal, Attentive, Courageous",
  },
  {
    id: 17,
    image: "https://cdn2.thedogapi.com/images/SkmRJl9VQ.jpg",
    name: "American Water Spaniel",
    height: { imperial: "15 - 18", metric: "38 - 46" },
    weight: { imperial: "25 - 45", metric: "11 - 20" },
    life_span: "10 - 12 years",
    temperament:
      "Friendly, Energetic, Obedient, Intelligent, Protective, Trainable",
  },
  {
    id: 18,
    image: "https://cdn2.thedogapi.com/images/BJT0Jx5Nm.jpg",
    name: "Anatolian Shepherd Dog",
    height: { imperial: "27 - 29", metric: "69 - 74" },
    weight: { imperial: "80 - 150", metric: "36 - 68" },
    life_span: "11 - 13 years",
    temperament: "Steady, Bold, Independent, Confident, Intelligent, Proud",
  },
  {
    id: 19,
    image: "https://cdn2.thedogapi.com/images/HkNkxlqEX.jpg",
    name: "Appenzeller Sennenhund",
    height: { imperial: "20 - 22", metric: "51 - 56" },
    weight: { imperial: "48 - 55", metric: "22 - 25" },
    life_span: "12 – 14 years",
    temperament: "Reliable, Fearless, Energetic, Lively, Self-assured",
  },
  {
    id: 21,
    image: "https://cdn2.thedogapi.com/images/IBkYVm4v1.jpg",
    name: "Australian Cattle Dog",
    height: { imperial: "17 - 20", metric: "43 - 51" },
    weight: { imperial: "44 - 62", metric: "20 - 28" },
    life_span: "12 - 14 years",
    temperament: "Cautious, Energetic, Loyal, Obedient, Protective, Brave",
  },
  {
    id: 22,
    image: "https://cdn2.thedogapi.com/images/Hyq1ge9VQ.jpg",
    name: "Australian Kelpie",
    height: { imperial: "17 - 20", metric: "43 - 51" },
    weight: { imperial: "31 - 46", metric: "14 - 21" },
    life_span: "10 - 13 years",
    temperament: "Friendly, Energetic, Alert, Loyal, Intelligent, Eager",
  },
  {
    id: 23,
    image: "https://cdn2.thedogapi.com/images/B1-llgq4m.jpg",
    name: "Australian Shepherd",
    height: { imperial: "18 - 23", metric: "46 - 58" },
    weight: { imperial: "35 - 65", metric: "16 - 29" },
    life_span: "12 - 16 years",
    temperament: "Good-natured, Affectionate, Intelligent, Active, Protective",
  },
  {
    id: 24,
    image: "https://cdn2.thedogapi.com/images/r1Ylge5Vm.jpg",
    name: "Australian Terrier",
    height: { imperial: "10 - 11", metric: "25 - 28" },
    weight: { imperial: "14 - 16", metric: "6 - 7" },
    life_span: "15 years",
    temperament:
      "Spirited, Alert, Loyal, Companionable, Even Tempered, Courageous",
  },
  {
    id: 25,
    image: "https://cdn2.thedogapi.com/images/SkvZgx94m.jpg",
    name: "Azawakh",
    height: { imperial: "23 - 29", metric: "58 - 74" },
    weight: { imperial: "33 - 55", metric: "15 - 25" },
    life_span: "10 - 13 years",
    temperament: "Aloof, Affectionate, Attentive, Rugged, Fierce, Refined",
  },
  {
    id: 26,
    image: "https://cdn2.thedogapi.com/images/HyWGexcVQ.jpg",
    name: "Barbet",
    height: { imperial: "20 - 26", metric: "51 - 66" },
    weight: { imperial: "40 - 65", metric: "18 - 29" },
    life_span: "13 – 15 years",
    temperament: "Obedient, Companionable, Intelligent, Joyful",
  },
  {
    id: 28,
    image: "https://cdn2.thedogapi.com/images/H1dGlxqNQ.jpg",
    name: "Basenji",
    height: { imperial: "16 - 17", metric: "41 - 43" },
    weight: { imperial: "22 - 24", metric: "10 - 11" },
    life_span: "10 - 12 years",
    temperament:
      "Affectionate, Energetic, Alert, Curious, Playful, Intelligent",
  },
  {
    id: 29,
    image: "https://cdn2.thedogapi.com/images/BkMQll94X.jpg",
    name: "Basset Bleu de Gascogne",
    height: { imperial: "13 - 15", metric: "33 - 38" },
    weight: { imperial: "35 - 40", metric: "16 - 18" },
    life_span: "10 - 14 years",
    temperament: "Affectionate, Lively, Agile, Curious, Happy, Active",
  },
  {
    id: 30,
    image: "https://cdn2.thedogapi.com/images/Sy57xx9EX.jpg",
    name: "Basset Hound",
    height: { imperial: "14", metric: "36" },
    weight: { imperial: "50 - 65", metric: "23 - 29" },
    life_span: "12 - 15 years",
    temperament:
      "Tenacious, Friendly, Affectionate, Devoted, Sweet-Tempered, Gentle",
  },
  {
    id: 31,
    image: "https://cdn2.thedogapi.com/images/Syd4xxqEm.jpg",
    name: "Beagle",
    height: { imperial: "13 - 15", metric: "33 - 38" },
    weight: { imperial: "20 - 35", metric: "9 - 16" },
    life_span: "13 - 16 years",
    temperament:
      "Amiable, Even Tempered, Excitable, Determined, Gentle, Intelligent",
  },
  {
    id: 32,
    image: "https://cdn2.thedogapi.com/images/A09F4c1qP.jpg",
    name: "Bearded Collie",
    height: { imperial: "20 - 22", metric: "51 - 56" },
    weight: { imperial: "45 - 55", metric: "20 - 25" },
    life_span: "12 - 14 years",
    temperament: "Self-confidence, Hardy, Lively, Alert, Intelligent, Active",
  },
  {
    id: 33,
    image: "https://cdn2.thedogapi.com/images/HJQ8ge5V7.jpg",
    name: "Beauceron",
    height: { imperial: "24 - 27.5", metric: "61 - 70" },
    weight: { imperial: "80 - 110", metric: "36 - 50" },
    life_span: "10 - 12 years",
    temperament: "Fearless, Friendly, Intelligent, Protective, Calm",
  },
  {
    id: 34,
    image: "https://cdn2.thedogapi.com/images/ByK8gx947.jpg",
    name: "Bedlington Terrier",
    height: { imperial: "15 - 16", metric: "38 - 41" },
    weight: { imperial: "17 - 23", metric: "8 - 10" },
    life_span: "14 - 16 years",
    temperament: "Affectionate, Spirited, Intelligent, Good-tempered",
  },
  {
    id: 36,
    image: "https://cdn2.thedogapi.com/images/r1f_ll5VX.jpg",
    name: "Belgian Malinois",
    height: { imperial: "22 - 26", metric: "56 - 66" },
    weight: { imperial: "40 - 80", metric: "18 - 36" },
    life_span: "12 - 14 years",
    temperament:
      "Watchful, Alert, Stubborn, Friendly, Confident, Hard-working, Active, Protective",
  },
  {
    id: 38,
    image: "https://cdn2.thedogapi.com/images/B1KdxlcNX.jpg",
    name: "Belgian Tervuren",
    height: { imperial: "22 - 26", metric: "56 - 66" },
    weight: { imperial: "40 - 65", metric: "18 - 29" },
    life_span: "10 - 12 years",
    temperament: "Energetic, Alert, Loyal, Intelligent, Attentive, Protective",
  },
  {
    id: 41,
    image: "https://cdn2.thedogapi.com/images/S1fFlx5Em.jpg",
    name: "Bernese Mountain Dog",
    height: { imperial: "23 - 27.5", metric: "58 - 70" },
    weight: { imperial: "65 - 120", metric: "29 - 54" },
    life_span: "7 - 10 years",
    temperament: "Affectionate, Loyal, Intelligent, Faithful",
  },
  {
    id: 42,
    image: "https://cdn2.thedogapi.com/images/HkuYlxqEQ.jpg",
    name: "Bichon Frise",
    height: { imperial: "9.5 - 11.5", metric: "24 - 29" },
    weight: { imperial: "10 - 18", metric: "5 - 8" },
    life_span: "15 years",
    temperament: "Feisty, Affectionate, Cheerful, Playful, Gentle, Sensitive",
  },
  {
    id: 43,
    image: "https://cdn2.thedogapi.com/images/HJAFgxcNQ.jpg",
    name: "Black and Tan Coonhound",
    height: { imperial: "23 - 27", metric: "58 - 69" },
    weight: { imperial: "65 - 100", metric: "29 - 45" },
    life_span: "10 - 12 years",
    temperament:
      "Easygoing, Gentle, Adaptable, Trusting, Even Tempered, Lovable",
  },
  {
    id: 45,
    image: "https://cdn2.thedogapi.com/images/Skdcgx9VX.jpg",
    name: "Bloodhound",
    height: { imperial: "23 - 27", metric: "58 - 69" },
    weight: { imperial: "80 - 110", metric: "36 - 50" },
    life_span: "8 - 10 years",
    temperament: "Stubborn, Affectionate, Gentle, Even Tempered",
  },
  {
    id: 47,
    image: "https://cdn2.thedogapi.com/images/rJxieg9VQ.jpg",
    name: "Bluetick Coonhound",
    height: { imperial: "21 - 27", metric: "53 - 69" },
    weight: { imperial: "45 - 80", metric: "20 - 36" },
    life_span: "12 - 14 years",
    temperament: "Friendly, Intelligent, Active",
  },
  {
    id: 48,
    image: "https://cdn2.thedogapi.com/images/HyOjge5Vm.jpg",
    name: "Boerboel",
    height: { imperial: "22 - 27", metric: "56 - 69" },
    weight: { imperial: "110 - 200", metric: "50 - 91" },
    life_span: "10 - 12 years",
    temperament: "Obedient, Confident, Intelligent, Dominant, Territorial",
  },
  {
    id: 50,
    image: "https://cdn2.thedogapi.com/images/sGQvQUpsp.jpg",
    name: "Border Collie",
    height: { imperial: "18 - 22", metric: "46 - 56" },
    weight: { imperial: "30 - 45", metric: "14 - 20" },
    life_span: "12 - 16 years",
    temperament: "Tenacious, Keen, Energetic, Responsive, Alert, Intelligent",
  },
  {
    id: 51,
    image: "https://cdn2.thedogapi.com/images/HJOpge9Em.jpg",
    name: "Border Terrier",
    height: { imperial: "11 - 16", metric: "28 - 41" },
    weight: { imperial: "11.5 - 15.5", metric: "5 - 7" },
    life_span: "12 - 14 years",
    temperament:
      "Fearless, Affectionate, Alert, Obedient, Intelligent, Even Tempered",
  },
  {
    id: 53,
    image: "https://cdn2.thedogapi.com/images/rkZRggqVX.jpg",
    name: "Boston Terrier",
    height: { imperial: "16 - 17", metric: "41 - 43" },
    weight: { imperial: "10 - 25", metric: "5 - 11" },
    life_span: "11 - 13 years",
    temperament: "Friendly, Lively, Intelligent",
  },
  {
    id: 54,
    image: "https://cdn2.thedogapi.com/images/Byd0xl5VX.jpg",
    name: "Bouvier des Flandres",
    height: { imperial: "23.5 - 27.5", metric: "60 - 70" },
    weight: { imperial: "70 - 110", metric: "32 - 50" },
    life_span: "10 - 15 years",
    temperament: "Protective, Loyal, Gentle, Intelligent, Familial, Rational",
  },
  {
    id: 55,
    image: "https://cdn2.thedogapi.com/images/ry1kWe5VQ.jpg",
    name: "Boxer",
    height: { imperial: "21.5 - 25", metric: "55 - 64" },
    weight: { imperial: "50 - 70", metric: "23 - 32" },
    life_span: "8 - 10 years",
    temperament:
      "Devoted, Fearless, Friendly, Cheerful, Energetic, Loyal, Playful, Confident, Intelligent, Bright, Brave, Calm",
  },
  {
    id: 56,
    image: "https://cdn2.thedogapi.com/images/ryHJZlcNX.jpg",
    name: "Boykin Spaniel",
    height: { imperial: "14 - 18", metric: "36 - 46" },
    weight: { imperial: "25 - 40", metric: "11 - 18" },
    life_span: "10 - 14 years",
    temperament:
      "Friendly, Energetic, Companionable, Intelligent, Eager, Trainable",
  },
  {
    id: 57,
    image: "https://cdn2.thedogapi.com/images/S13yZg5VQ.jpg",
    name: "Bracco Italiano",
    height: { imperial: "21.5 - 26.5", metric: "55 - 67" },
    weight: { imperial: "55 - 88", metric: "25 - 40" },
    life_span: "10 - 12 years",
    temperament:
      "Stubborn, Affectionate, Loyal, Playful, Companionable, Trainable",
  },
  {
    id: 58,
    image: "https://cdn2.thedogapi.com/images/rkVlblcEQ.jpg",
    name: "Briard",
    height: { imperial: "22 - 27", metric: "56 - 69" },
    weight: { imperial: "70 - 90", metric: "32 - 41" },
    life_span: "10 - 12 years",
    temperament: "Fearless, Loyal, Obedient, Intelligent, Faithful, Protective",
  },
  {
    id: 59,
    image: "https://cdn2.thedogapi.com/images/HJWZZxc4X.jpg",
    name: "Brittany",
    height: { imperial: "17.5 - 20.5", metric: "44 - 52" },
    weight: { imperial: "30 - 45", metric: "14 - 20" },
    life_span: "12 - 14 years",
    temperament: "Agile, Adaptable, Quick, Intelligent, Attentive, Happy",
  },
  {
    id: 61,
    image: "https://cdn2.thedogapi.com/images/VSraIEQGd.jpg",
    name: "Bull Terrier",
    height: { imperial: "21 - 22", metric: "53 - 56" },
    weight: { imperial: "50 - 70", metric: "23 - 32" },
    life_span: "10 - 12 years",
    temperament: "Trainable, Protective, Sweet-Tempered, Keen, Active",
  },
  {
    id: 62,
    image: "https://cdn2.thedogapi.com/images/BkKZWlcVX.jpg",
    name: "Bull Terrier (Miniature)",
    height: { imperial: "10 - 14", metric: "25 - 36" },
    weight: { imperial: "25 - 33", metric: "11 - 15" },
    life_span: "11 – 14 years",
    temperament:
      "Trainable, Protective, Sweet-Tempered, Keen, Active, Territorial",
  },
  {
    id: 64,
    image: "https://cdn2.thedogapi.com/images/r1ifZl5E7.jpg",
    name: "Bullmastiff",
    height: { imperial: "24 - 27", metric: "61 - 69" },
    weight: { imperial: "100 - 130", metric: "45 - 59" },
    life_span: "8 - 12 years",
    temperament:
      "Docile, Reliable, Devoted, Alert, Loyal, Reserved, Loving, Protective, Powerful, Calm, Courageous",
  },
  {
    id: 65,
    image: "https://cdn2.thedogapi.com/images/Sk7Qbg9E7.jpg",
    name: "Cairn Terrier",
    height: { imperial: "9 - 10", metric: "23 - 25" },
    weight: { imperial: "13 - 14", metric: "6 - 6" },
    life_span: "14 - 15 years",
    temperament: "Hardy, Fearless, Assertive, Gay, Intelligent, Active",
  },
  {
    id: 67,
    image: "https://cdn2.thedogapi.com/images/r15m-lc4m.jpg",
    name: "Cane Corso",
    height: { imperial: "23.5 - 27.5", metric: "60 - 70" },
    weight: { imperial: "88 - 120", metric: "40 - 54" },
    life_span: "10 - 11 years",
    temperament: "Trainable, Reserved, Stable, Quiet, Even Tempered, Calm",
  },
  {
    id: 68,
    image: "https://cdn2.thedogapi.com/images/SyXN-e9NX.jpg",
    name: "Cardigan Welsh Corgi",
    height: { imperial: "10.5 - 12.5", metric: "27 - 32" },
    weight: { imperial: "25 - 38", metric: "11 - 17" },
    life_span: "12 - 14 years",
    temperament:
      "Affectionate, Devoted, Alert, Companionable, Intelligent, Active",
  },
  {
    id: 69,
    image: "https://cdn2.thedogapi.com/images/BJcNbec4X.jpg",
    name: "Catahoula Leopard Dog",
    height: { imperial: "20 - 26", metric: "51 - 66" },
    weight: { imperial: "50 - 95", metric: "23 - 43" },
    life_span: "10 - 12 years",
    temperament:
      "Energetic, Inquisitive, Independent, Gentle, Intelligent, Loving",
  },
  {
    id: 70,
    image: "https://cdn2.thedogapi.com/images/r1rrWe5Em.jpg",
    name: "Caucasian Shepherd (Ovcharka)",
    height: { imperial: "24 - 33.5", metric: "61 - 85" },
    weight: { imperial: "80 - 100", metric: "36 - 45" },
    life_span: "10 - 12 years",
    temperament: "Alert, Quick, Dominant, Powerful, Calm, Strong",
  },
  {
    id: 71,
    image: "https://cdn2.thedogapi.com/images/HJRBbe94Q.jpg",
    name: "Cavalier King Charles Spaniel",
    height: { imperial: "12 - 13", metric: "30 - 33" },
    weight: { imperial: "13 - 18", metric: "6 - 8" },
    life_span: "10 - 14 years",
    temperament:
      "Fearless, Affectionate, Sociable, Patient, Playful, Adaptable",
  },
  {
    id: 76,
    image: "https://cdn2.thedogapi.com/images/9BXwUeCc2.jpg",
    name: "Chesapeake Bay Retriever",
    height: { imperial: "21 - 26", metric: "53 - 66" },
    weight: { imperial: "55 - 80", metric: "25 - 36" },
    life_span: "10 - 13 years",
    temperament:
      "Affectionate, Intelligent, Quiet, Dominant, Happy, Protective",
  },
  {
    id: 78,
    image: "https://cdn2.thedogapi.com/images/B1pDZx9Nm.jpg",
    name: "Chinese Crested",
    height: { imperial: "11 - 13", metric: "28 - 33" },
    weight: { imperial: "10 - 13", metric: "5 - 6" },
    life_span: "10 - 14 years",
    temperament: "Affectionate, Sweet-Tempered, Lively, Alert, Playful, Happy",
  },
  {
    id: 79,
    image: "https://cdn2.thedogapi.com/images/B1ruWl94Q.jpg",
    name: "Chinese Shar-Pei",
    height: { imperial: "18 - 20", metric: "46 - 51" },
    weight: { imperial: "45 - 60", metric: "20 - 27" },
    life_span: "10 years",
    temperament:
      "Suspicious, Affectionate, Devoted, Reserved, Independent, Loving",
  },
  {
    id: 80,
    image: "https://cdn2.thedogapi.com/images/Sypubg54Q.jpg",
    name: "Chinook",
    height: { imperial: "22 - 26", metric: "56 - 66" },
    weight: { imperial: "50 - 90", metric: "23 - 41" },
    life_span: "12 - 15 years",
    temperament: "Friendly, Alert, Dignified, Intelligent, Calm",
  },
  {
    id: 81,
    image: "https://cdn2.thedogapi.com/images/ry8KWgqEQ.jpg",
    name: "Chow Chow",
    height: { imperial: "17 - 20", metric: "43 - 51" },
    weight: { imperial: "40 - 70", metric: "18 - 32" },
    life_span: "12 - 15 years",
    temperament: "Aloof, Loyal, Independent, Quiet",
  },
  {
    id: 84,
    image: "https://cdn2.thedogapi.com/images/rkeqWgq4Q.jpg",
    name: "Clumber Spaniel",
    height: { imperial: "17 - 20", metric: "43 - 51" },
    weight: { imperial: "55 - 85", metric: "25 - 39" },
    life_span: "10 - 12 years",
    temperament: "Affectionate, Loyal, Dignified, Gentle, Calm, Great-hearted",
  },
  {
    id: 86,
    image: "https://cdn2.thedogapi.com/images/1lFmrzECl.jpg",
    name: "Cocker Spaniel",
    height: { imperial: "14 - 15", metric: "36 - 38" },
    weight: { imperial: "20 - 30", metric: "9 - 14" },
    life_span: "12 - 15 years",
    temperament: "Trainable, Friendly, Affectionate, Playful, Quiet, Faithful",
  },
  {
    id: 87,
    image: "https://cdn2.thedogapi.com/images/HkRcZe547.jpg",
    name: "Cocker Spaniel (American)",
    height: { imperial: "14 - 15", metric: "36 - 38" },
    weight: { imperial: "20 - 30", metric: "9 - 14" },
    life_span: "12 - 15 years",
    temperament: "Outgoing, Sociable, Trusting, Joyful, Even Tempered, Merry",
  },
  {
    id: 89,
    image: "https://cdn2.thedogapi.com/images/SyviZlqNm.jpg",
    name: "Coton de Tulear",
    height: { imperial: "9 - 11", metric: "23 - 28" },
    weight: { imperial: "9 - 15", metric: "4 - 7" },
    life_span: "13 - 16 years",
    temperament: "Affectionate, Lively, Playful, Intelligent, Trainable, Vocal",
  },
  {
    id: 92,
    image: "https://cdn2.thedogapi.com/images/SkJ3blcN7.jpg",
    name: "Dalmatian",
    height: { imperial: "19 - 23", metric: "48 - 58" },
    weight: { imperial: "50 - 55", metric: "23 - 25" },
    life_span: "10 - 13 years",
    temperament:
      "Outgoing, Friendly, Energetic, Playful, Sensitive, Intelligent, Active",
  },
  {
    id: 94,
    image: "https://cdn2.thedogapi.com/images/HyL3bl94Q.jpg",
    name: "Doberman Pinscher",
    height: { imperial: "24 - 28", metric: "61 - 71" },
    weight: { imperial: "66 - 88", metric: "30 - 40" },
    life_span: "10 years",
    temperament:
      "Fearless, Energetic, Alert, Loyal, Obedient, Confident, Intelligent",
  },
  {
    id: 95,
    image: "https://cdn2.thedogapi.com/images/S1nhWx94Q.jpg",
    name: "Dogo Argentino",
    height: { imperial: "23.5 - 27", metric: "60 - 69" },
    weight: { imperial: "80 - 100", metric: "36 - 45" },
    life_span: "10 - 12 years",
    temperament:
      "Friendly, Affectionate, Cheerful, Loyal, Tolerant, Protective",
  },
  {
    id: 98,
    image: "https://cdn2.thedogapi.com/images/BkE6Wg5E7.jpg",
    name: "Dutch Shepherd",
    height: { imperial: "22 - 24.5", metric: "56 - 62" },
    weight: { imperial: "50 - 70", metric: "23 - 32" },
    life_span: "15 years",
    temperament: "Reliable, Affectionate, Alert, Loyal, Obedient, Trainable",
  },
  {
    id: 101,
    image: "https://cdn2.thedogapi.com/images/By4A-eqVX.jpg",
    name: "English Setter",
    height: { imperial: "24 - 25", metric: "61 - 64" },
    weight: { imperial: "45 - 80", metric: "20 - 36" },
    life_span: "12 years",
    temperament:
      "Strong Willed, Mischievous, Affectionate, Energetic, Playful, Companionable, Gentle, Hard-working, Intelligent, Eager, People-Oriented",
  },
  {
    id: 102,
    image: "https://cdn2.thedogapi.com/images/H1QyMe5EQ.jpg",
    name: "English Shepherd",
    height: { imperial: "18 - 23", metric: "46 - 58" },
    weight: { imperial: "44 - 66", metric: "20 - 30" },
    life_span: "10 - 13 years",
    temperament: "Kind, Energetic, Independent, Adaptable, Intelligent, Bossy",
  },
  {
    id: 103,
    image: "https://cdn2.thedogapi.com/images/Hk0Jfe5VQ.jpg",
    name: "English Springer Spaniel",
    height: { imperial: "19 - 20", metric: "48 - 51" },
    weight: { imperial: "35 - 50", metric: "16 - 23" },
    life_span: "12 - 14 years",
    temperament:
      "Affectionate, Cheerful, Alert, Intelligent, Attentive, Active",
  },
  {
    id: 104,
    image: "https://cdn2.thedogapi.com/images/SkIgzxqNQ.jpg",
    name: "English Toy Spaniel",
    height: { imperial: "10", metric: "25" },
    weight: { imperial: "8 - 14", metric: "4 - 6" },
    life_span: "10 - 12 years",
    temperament: "Affectionate, Reserved, Playful, Gentle, Happy, Loving",
  },
  {
    id: 105,
    image: "https://cdn2.thedogapi.com/images/SJ6eMxqEQ.jpg",
    name: "English Toy Terrier",
    height: { imperial: "10 - 12", metric: "25 - 30" },
    weight: { imperial: "6 - 8", metric: "3 - 4" },
    life_span: "12 - 13 years",
    temperament:
      "Stubborn, Alert, Companionable, Intelligent, Cunning, Trainable",
  },
  {
    id: 107,
    image: "https://cdn2.thedogapi.com/images/S1VWGx9Nm.jpg",
    name: "Eurasier",
    height: { imperial: "20.5 - 23.5", metric: "52 - 60" },
    weight: { imperial: "40 - 70", metric: "18 - 32" },
    life_span: "12 - 14 years",
    temperament: "Alert, Reserved, Intelligent, Even Tempered, Watchful, Calm",
  },
  {
    id: 108,
    image: "https://cdn2.thedogapi.com/images/SkJfGecE7.jpg",
    name: "Field Spaniel",
    height: { imperial: "17 - 18", metric: "43 - 46" },
    weight: { imperial: "35 - 50", metric: "16 - 23" },
    life_span: "11 - 15 years",
    temperament: "Docile, Cautious, Sociable, Sensitive, Adaptable, Familial",
  },
  {
    id: 110,
    image: "https://cdn2.thedogapi.com/images/S1KMGg5Vm.jpg",
    name: "Finnish Lapphund",
    height: { imperial: "16 - 21", metric: "41 - 53" },
    weight: { imperial: "33 - 53", metric: "15 - 24" },
    life_span: "12 - 15 years",
    temperament: "Friendly, Keen, Faithful, Calm, Courageous",
  },
  {
    id: 111,
    image: "https://cdn2.thedogapi.com/images/3PjHlQbkV.jpg",
    name: "Finnish Spitz",
    height: { imperial: "15.5 - 20", metric: "39 - 51" },
    weight: { imperial: "23 - 28", metric: "10 - 13" },
    life_span: "12 - 15 years",
    temperament: "Playful, Loyal, Independent, Intelligent, Happy, Vocal",
  },
  {
    id: 113,
    image: "https://cdn2.thedogapi.com/images/HyWNfxc47.jpg",
    name: "French Bulldog",
    height: { imperial: "11 - 12", metric: "28 - 30" },
    weight: { imperial: "28", metric: "13" },
    life_span: "9 - 11 years",
    temperament:
      "Playful, Affectionate, Keen, Sociable, Lively, Alert, Easygoing, Patient, Athletic, Bright",
  },
  {
    id: 114,
    image: "https://cdn2.thedogapi.com/images/B1u4zgqE7.jpg",
    name: "German Pinscher",
    height: { imperial: "17 - 20", metric: "43 - 51" },
    weight: { imperial: "25 - 45", metric: "11 - 20" },
    life_span: "12 - 14 years",
    temperament:
      "Spirited, Lively, Intelligent, Loving, Even Tempered, Familial",
  },
  {
    id: 115,
    image: "https://cdn2.thedogapi.com/images/SJyBfg5NX.jpg",
    name: "German Shepherd Dog",
    height: { imperial: "22 - 26", metric: "56 - 66" },
    weight: { imperial: "50 - 90", metric: "23 - 41" },
    life_span: "10 - 13 years",
    temperament:
      "Alert, Loyal, Obedient, Curious, Confident, Intelligent, Watchful, Courageous",
  },
  {
    id: 116,
    image: "https://cdn2.thedogapi.com/images/SJqBMg5Nm.jpg",
    name: "German Shorthaired Pointer",
    height: { imperial: "21 - 25", metric: "53 - 64" },
    weight: { imperial: "45 - 70", metric: "20 - 32" },
    life_span: "12 - 14 years",
    temperament:
      "Boisterous, Bold, Affectionate, Intelligent, Cooperative, Trainable",
  },
  {
    id: 119,
    image: "https://cdn2.thedogapi.com/images/H1NIzlcV7.jpg",
    name: "Giant Schnauzer",
    height: { imperial: "23.5 - 27.5", metric: "60 - 70" },
    weight: { imperial: "65 - 90", metric: "29 - 41" },
    life_span: "10 - 12 years",
    temperament: "Strong Willed, Kind, Loyal, Intelligent, Dominant, Powerful",
  },
  {
    id: 120,
    image: "https://cdn2.thedogapi.com/images/H1oLMe94m.jpg",
    name: "Glen of Imaal Terrier",
    height: { imperial: "12.5 - 14", metric: "32 - 36" },
    weight: { imperial: "32 - 40", metric: "15 - 18" },
    life_span: "12 - 15 years",
    temperament: "Spirited, Agile, Loyal, Gentle, Active, Courageous",
  },
  {
    id: 121,
    image: "https://cdn2.thedogapi.com/images/HJ7Pzg5EQ.jpg",
    name: "Golden Retriever",
    height: { imperial: "21.5 - 24", metric: "55 - 61" },
    weight: { imperial: "55 - 75", metric: "25 - 34" },
    life_span: "10 - 12 years",
    temperament:
      "Intelligent, Kind, Reliable, Friendly, Trustworthy, Confident",
  },
  {
    id: 123,
    image: "https://cdn2.thedogapi.com/images/SJ5vzx5NX.jpg",
    name: "Gordon Setter",
    height: { imperial: "23 - 27", metric: "58 - 69" },
    weight: { imperial: "45 - 80", metric: "20 - 36" },
    life_span: "10 - 12 years",
    temperament: "Fearless, Alert, Loyal, Confident, Gay, Eager",
  },
  {
    id: 124,
    image: "https://cdn2.thedogapi.com/images/B1Edfl9NX.jpg",
    name: "Great Dane",
    height: { imperial: "28 - 32", metric: "71 - 81" },
    weight: { imperial: "110 - 190", metric: "50 - 86" },
    life_span: "7 - 10 years",
    temperament: "Friendly, Devoted, Reserved, Gentle, Confident, Loving",
  },
  {
    id: 125,
    image: "https://cdn2.thedogapi.com/images/B12uzg9V7.jpg",
    name: "Great Pyrenees",
    height: { imperial: "25 - 32", metric: "64 - 81" },
    weight: { imperial: "85 - 115", metric: "39 - 52" },
    life_span: "10 - 12 years",
    temperament:
      "Strong Willed, Fearless, Affectionate, Patient, Gentle, Confident",
  },
  {
    id: 127,
    image: "https://cdn2.thedogapi.com/images/ryNYMx94X.jpg",
    name: "Greyhound",
    height: { imperial: "27 - 30", metric: "69 - 76" },
    weight: { imperial: "50 - 70", metric: "23 - 32" },
    life_span: "10 - 13 years",
    temperament:
      "Affectionate, Athletic, Gentle, Intelligent, Quiet, Even Tempered",
  },
  {
    id: 128,
    image: "https://cdn2.thedogapi.com/images/ryoYGec4Q.jpg",
    name: "Griffon Bruxellois",
    height: { imperial: "9 - 11", metric: "23 - 28" },
    weight: { imperial: "12", metric: "5" },
    life_span: "10 – 15 years",
    temperament:
      "Self-important, Inquisitive, Alert, Companionable, Sensitive, Watchful",
  },
  {
    id: 129,
    image: "https://cdn2.thedogapi.com/images/B1IcfgqE7.jpg",
    name: "Harrier",
    height: { imperial: "18 - 22", metric: "46 - 56" },
    weight: { imperial: "40 - 60", metric: "18 - 27" },
    life_span: "12 - 15 years",
    temperament:
      "Outgoing, Friendly, Cheerful, Sweet-Tempered, Tolerant, Active",
  },
  {
    id: 130,
    image: "https://cdn2.thedogapi.com/images/rkXiGl9V7.jpg",
    name: "Havanese",
    height: { imperial: "8.5 - 11.5", metric: "22 - 29" },
    weight: { imperial: "7 - 13", metric: "3 - 6" },
    life_span: "14 - 15 years",
    temperament:
      "Affectionate, Responsive, Playful, Companionable, Gentle, Intelligent",
  },
  {
    id: 134,
    image: "https://cdn2.thedogapi.com/images/S1osGeqVm.jpg",
    name: "Irish Setter",
    height: { imperial: "24 - 27", metric: "61 - 69" },
    weight: { imperial: "35 - 70", metric: "16 - 32" },
    life_span: "10 - 11 years",
    temperament:
      "Affectionate, Energetic, Lively, Independent, Playful, Companionable",
  },
  {
    id: 135,
    image: "https://cdn2.thedogapi.com/images/By-hGecVX.jpg",
    name: "Irish Terrier",
    height: { imperial: "18", metric: "46" },
    weight: { imperial: "25 - 27", metric: "11 - 12" },
    life_span: "12 - 16 years",
    temperament:
      "Respectful, Lively, Intelligent, Dominant, Protective, Trainable",
  },
  {
    id: 137,
    image: "https://cdn2.thedogapi.com/images/Hyd2zgcEX.jpg",
    name: "Irish Wolfhound",
    height: { imperial: "30 - 35", metric: "76 - 89" },
    weight: { imperial: "105 - 180", metric: "48 - 82" },
    life_span: "6 - 8 years",
    temperament:
      "Sweet-Tempered, Loyal, Dignified, Patient, Thoughtful, Generous",
  },
  {
    id: 138,
    image: "https://cdn2.thedogapi.com/images/SJAnzg9NX.jpg",
    name: "Italian Greyhound",
    height: { imperial: "13 - 15", metric: "33 - 38" },
    weight: { imperial: "7 - 15", metric: "3 - 7" },
    life_span: "12 - 15 years",
    temperament:
      "Mischievous, Affectionate, Agile, Athletic, Companionable, Intelligent",
  },
  {
    id: 140,
    image: "https://cdn2.thedogapi.com/images/r1H6feqEm.jpg",
    name: "Japanese Chin",
    height: { imperial: "8 - 11", metric: "20 - 28" },
    weight: { imperial: "4 - 9", metric: "2 - 4" },
    life_span: "12 - 14 years",
    temperament: "Alert, Loyal, Independent, Intelligent, Loving, Cat-like",
  },
  {
    id: 141,
    image: "https://cdn2.thedogapi.com/images/HksaMxqNX.jpg",
    name: "Japanese Spitz",
    height: { imperial: "12 - 15", metric: "30 - 38" },
    weight: { imperial: "15 - 19", metric: "7 - 9" },
    life_span: "10 – 16 years",
    temperament:
      "Affectionate, Obedient, Playful, Companionable, Intelligent, Proud",
  },
];

const temps = [
  { id: 1, name: "Stubborn" },
  { id: 2, name: "Curious" },
  { id: 3, name: "Playful" },
  { id: 4, name: "Adventurous" },
  { id: 5, name: "Active" },
  { id: 6, name: "Fun-loving" },
  { id: 7, name: "Aloof" },
  { id: 8, name: "Clownish" },
  { id: 9, name: "Dignified" },
  { id: 10, name: "Independent" },
  { id: 11, name: "Happy" },
  { id: 12, name: "Hardworking" },
  { id: 13, name: "Dutiful" },
  { id: 14, name: "Outgoing" },
  { id: 15, name: "Wild" },
  { id: 16, name: "Alert" },
  { id: 17, name: "Confident" },
  { id: 18, name: "Friendly" },
  { id: 19, name: "Intelligent" },
  { id: 20, name: "Courageous" },
  { id: 21, name: "Docile" },
  { id: 22, name: "Responsive" },
  { id: 23, name: "Composed" },
  { id: 24, name: "Receptive" },
  { id: 25, name: "Loyal" },
  { id: 26, name: "Faithful" },
  { id: 27, name: "Brave" },
  { id: 28, name: "Loving" },
  { id: 29, name: "Protective" },
  { id: 30, name: "Trainable" },
  { id: 31, name: "Responsible" },
  { id: 32, name: "Energetic" },
  { id: 33, name: "Gentle" },
  { id: 34, name: "Affectionate" },
  { id: 35, name: "Devoted" },
  { id: 36, name: "Assertive" },
  { id: 37, name: "Dominant" },
  { id: 38, name: "Strong Willed" },
  { id: 39, name: "Obedient" },
  { id: 40, name: "Reserved" },
  { id: 41, name: "Kind" },
  { id: 42, name: "Sweet-Tempered" },
  { id: 43, name: "Tenacious" },
  { id: 44, name: "Attentive" },
  { id: 45, name: "Steady" },
  { id: 46, name: "Bold" },
  { id: 47, name: "Proud" },
  { id: 48, name: "Reliable" },
  { id: 49, name: "Fearless" },
  { id: 50, name: "Lively" },
  { id: 51, name: "Self-assured" },
  { id: 52, name: "Cautious" },
  { id: 53, name: "Eager" },
  { id: 54, name: "Good-natured" },
  { id: 55, name: "Spirited" },
  { id: 56, name: "Companionable" },
  { id: 57, name: "Even Tempered" },
  { id: 58, name: "Rugged" },
  { id: 59, name: "Fierce" },
  { id: 60, name: "Joyful" },
  { id: 61, name: "Refined" },
  { id: 62, name: "Agile" },
  { id: 63, name: "Amiable" },
  { id: 64, name: "Excitable" },
  { id: 65, name: "Determined" },
  { id: 66, name: "Self-confidence" },
  { id: 67, name: "Hardy" },
  { id: 68, name: "Calm" },
  { id: 69, name: "Good-tempered" },
  { id: 70, name: "Watchful" },
  { id: 71, name: "Hard-working" },
  { id: 72, name: "Feisty" },
  { id: 73, name: "Cheerful" },
  { id: 74, name: "Sensitive" },
  { id: 75, name: "Easygoing" },
  { id: 76, name: "Adaptable" },
  { id: 77, name: "Trusting" },
  { id: 78, name: "Lovable" },
  { id: 79, name: "Territorial" },
  { id: 80, name: "Keen" },
  { id: 81, name: "Familial" },
  { id: 82, name: "Rational" },
  { id: 83, name: "Bright" },
  { id: 84, name: "Quick" },
  { id: 85, name: "Powerful" },
  { id: 86, name: "Gay" },
  { id: 87, name: "Stable" },
  { id: 88, name: "Quiet" },
  { id: 89, name: "Inquisitive" },
  { id: 90, name: "Strong" },
  { id: 91, name: "Sociable" },
  { id: 92, name: "Patient" },
  { id: 93, name: "Suspicious" },
  { id: 94, name: "Great-hearted" },
  { id: 95, name: "Merry" },
  { id: 96, name: "Vocal" },
  { id: 97, name: "Tolerant" },
  { id: 98, name: "Mischievous" },
  { id: 99, name: "People-Oriented" },
  { id: 100, name: "Bossy" },
  { id: 101, name: "Cunning" },
  { id: 102, name: "Athletic" },
  { id: 103, name: "Boisterous" },
  { id: 104, name: "Cooperative" },
  { id: 105, name: "Trustworthy" },
  { id: 106, name: "Self-important" },
  { id: 107, name: "Respectful" },
  { id: 108, name: "Thoughtful" },
  { id: 109, name: "Generous" },
  { id: 110, name: "Cat-like" },
  { id: 111, name: "Sturdy" },
  { id: 112, name: "Benevolent" },
  { id: 113, name: "Bubbly" },
  { id: 114, name: "Clever" },
  { id: 115, name: "Opinionated" },
  { id: 116, name: "Aggressive" },
  { id: 117, name: "Extroverted" },
  { id: 118, name: "Charming" },
  { id: 119, name: "Unflappable" },
  { id: 120, name: "Spunky" },
  { id: 121, name: "Diligent" },
  { id: 122, name: "Willful" },
  { id: 123, name: "Vigilant" },
  { id: 124, name: "Fast" },
];

export { dogs, temps };
